#!/bin/bash

echo $0
echo $1
echo $2

if [ -z "$2" ]
then
  echo "Usage: profile_thumb orignal_file thumb_nail"
  exit 85
fi

convert $1 -resize 400x266 -gravity center -crop 400x266+0+0 +repage $2
#convert Gemfile -resize 400x266 -gravity center -crop 400x266+0+0 +repage
